branches:
  except:
    - /dev.*/  # do not build dev branch

image:
  - Visual Studio 2019

platform:
  - x86

configuration:
  - Debug
  - Release

environment:
  VCPKG_ROOT: C:\tools\vcpkg

install:
  - git submodule init
  - git submodule update
  - powershell .\scripts\prepare.ps1
  - set /p APP_ID=<app_id.txt

build_script:
  - powershell .\scripts\generate.ps1 %CONFIGURATION%
  - powershell .\scripts\build.ps1 %CONFIGURATION%

artifacts:
  - path: build/Release/Release/%APP_ID%
    type: zip
